# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
